import { settlementsData as telanganaSettlements } from './settlements.js';
import { safeSitesData as telanganaSafeSites } from './safeSites.js';
import { hazardZonesData as telanganaHazards } from './hazards.js';

export const allSettlementsData = [
  ...telanganaSettlements,

  // KERALA
  {
    name: 'Chooralmala Hamlet',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.155, 11.520] },
    elevation: 840,
    population: 3450,
    children: 820, elderly: 490, disabled: 110, lowIncome: 1650, pregnantWomen: 55,
    floodRisk: 85, landslideRisk: 98, cycloneRisk: 40, heatRisk: 30, infrastructureRisk: 92,
    roadAccessibility: 20, healthcareAccess: 25, educationAccess: 35, waterAccess: 40,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },
  {
    name: 'Mundakkai Settlement',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.175, 11.535] },
    elevation: 910,
    population: 2820,
    children: 680, elderly: 410, disabled: 95, lowIncome: 1400, pregnantWomen: 42,
    floodRisk: 80, landslideRisk: 99, cycloneRisk: 35, heatRisk: 28, infrastructureRisk: 95,
    roadAccessibility: 18, healthcareAccess: 20, educationAccess: 30, waterAccess: 35,
    hazardScore: 96, riskLevel: 'CRITICAL', priorityScore: 99, priorityLevel: 'URGENT',
  },
  {
    name: 'Meppadi Outskirts',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.128, 11.550] },
    elevation: 790,
    population: 4120,
    children: 980, elderly: 560, disabled: 130, lowIncome: 1950, pregnantWomen: 68,
    floodRisk: 75, landslideRisk: 90, cycloneRisk: 42, heatRisk: 32, infrastructureRisk: 85,
    roadAccessibility: 28, healthcareAccess: 32, educationAccess: 42, waterAccess: 45,
    hazardScore: 86, riskLevel: 'CRITICAL', priorityScore: 92, priorityLevel: 'URGENT',
  },
  {
    name: 'Kuttanad Waterway Village',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.380, 9.420] },
    elevation: -2,
    population: 5600,
    children: 1350, elderly: 820, disabled: 180, lowIncome: 2600, pregnantWomen: 95,
    floodRisk: 98, landslideRisk: 10, cycloneRisk: 68, heatRisk: 45, infrastructureRisk: 88,
    roadAccessibility: 22, healthcareAccess: 30, educationAccess: 45, waterAccess: 30,
    hazardScore: 91, riskLevel: 'CRITICAL', priorityScore: 95, priorityLevel: 'URGENT',
  },
  {
    name: 'Munnar Slope Colony',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [77.060, 10.088] },
    elevation: 1530,
    population: 3890,
    children: 920, elderly: 510, disabled: 125, lowIncome: 1850, pregnantWomen: 62,
    floodRisk: 78, landslideRisk: 92, cycloneRisk: 30, heatRisk: 20, infrastructureRisk: 86,
    roadAccessibility: 25, healthcareAccess: 28, educationAccess: 38, waterAccess: 42,
    hazardScore: 88, riskLevel: 'CRITICAL', priorityScore: 93, priorityLevel: 'URGENT',
  },
  {
    name: 'Chalakudy Riverbank',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.320, 10.300] },
    elevation: 25,
    population: 6400,
    children: 1520, elderly: 880, disabled: 210, lowIncome: 2800, pregnantWomen: 110,
    floodRisk: 92, landslideRisk: 25, cycloneRisk: 55, heatRisk: 42, infrastructureRisk: 76,
    roadAccessibility: 38, healthcareAccess: 42, educationAccess: 52, waterAccess: 48,
    hazardScore: 82, riskLevel: 'HIGH', priorityScore: 85, priorityLevel: 'HIGH',
  },
  {
    name: 'Ranni Lowland',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.780, 9.380] },
    elevation: 45,
    population: 4500,
    children: 1050, elderly: 620, disabled: 145, lowIncome: 1980, pregnantWomen: 75,
    floodRisk: 86, landslideRisk: 48, cycloneRisk: 45, heatRisk: 38, infrastructureRisk: 74,
    roadAccessibility: 35, healthcareAccess: 38, educationAccess: 48, waterAccess: 45,
    hazardScore: 78, riskLevel: 'HIGH', priorityScore: 82, priorityLevel: 'HIGH',
  },

  // ODISHA
  {
    name: 'Puri Beachfront Fishery Colony',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [85.830, 19.800] },
    elevation: 4,
    population: 6800,
    children: 1750, elderly: 890, disabled: 220, lowIncome: 3400, pregnantWomen: 120,
    floodRisk: 94, landslideRisk: 5, cycloneRisk: 99, heatRisk: 70, infrastructureRisk: 92,
    roadAccessibility: 24, healthcareAccess: 28, educationAccess: 35, waterAccess: 28,
    hazardScore: 96, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },
  {
    name: 'Paradip Port Lowland',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [86.610, 20.260] },
    elevation: 3,
    population: 8400,
    children: 2100, elderly: 1100, disabled: 280, lowIncome: 4100, pregnantWomen: 155,
    floodRisk: 92, landslideRisk: 5, cycloneRisk: 98, heatRisk: 68, infrastructureRisk: 90,
    roadAccessibility: 28, healthcareAccess: 32, educationAccess: 40, waterAccess: 32,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Kendrapara Marsh Hamlet',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [86.420, 20.500] },
    elevation: 8,
    population: 4950,
    children: 1280, elderly: 690, disabled: 165, lowIncome: 2550, pregnantWomen: 92,
    floodRisk: 96, landslideRisk: 5, cycloneRisk: 94, heatRisk: 65, infrastructureRisk: 88,
    roadAccessibility: 20, healthcareAccess: 24, educationAccess: 32, waterAccess: 26,
    hazardScore: 92, riskLevel: 'CRITICAL', priorityScore: 95, priorityLevel: 'URGENT',
  },
  {
    name: 'Balasore Coastal Delta',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [86.930, 21.490] },
    elevation: 6,
    population: 5200,
    children: 1320, elderly: 740, disabled: 175, lowIncome: 2680, pregnantWomen: 98,
    floodRisk: 88, landslideRisk: 5, cycloneRisk: 93, heatRisk: 66, infrastructureRisk: 84,
    roadAccessibility: 30, healthcareAccess: 32, educationAccess: 42, waterAccess: 35,
    hazardScore: 88, riskLevel: 'CRITICAL', priorityScore: 91, priorityLevel: 'URGENT',
  },
  {
    name: 'Chandbali River Delta',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [86.740, 20.780] },
    elevation: 7,
    population: 4100,
    children: 1020, elderly: 580, disabled: 135, lowIncome: 2050, pregnantWomen: 76,
    floodRisk: 91, landslideRisk: 5, cycloneRisk: 89, heatRisk: 64, infrastructureRisk: 80,
    roadAccessibility: 32, healthcareAccess: 35, educationAccess: 44, waterAccess: 36,
    hazardScore: 85, riskLevel: 'HIGH', priorityScore: 87, priorityLevel: 'HIGH',
  },
  {
    name: 'Ganjam Rushikulya Mouth',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [85.050, 19.360] },
    elevation: 5,
    population: 5700,
    children: 1420, elderly: 790, disabled: 190, lowIncome: 2850, pregnantWomen: 105,
    floodRisk: 82, landslideRisk: 8, cycloneRisk: 90, heatRisk: 72, infrastructureRisk: 78,
    roadAccessibility: 35, healthcareAccess: 38, educationAccess: 46, waterAccess: 40,
    hazardScore: 83, riskLevel: 'HIGH', priorityScore: 85, priorityLevel: 'HIGH',
  },

  // ASSAM
  {
    name: 'Majuli Island Sandbar Colony',
    regionName: 'Assam',
    location: { type: 'Point', coordinates: [94.210, 26.950] },
    elevation: 85,
    population: 4800,
    children: 1250, elderly: 690, disabled: 160, lowIncome: 2500, pregnantWomen: 95,
    floodRisk: 99, landslideRisk: 10, cycloneRisk: 30, heatRisk: 40, infrastructureRisk: 95,
    roadAccessibility: 12, healthcareAccess: 18, educationAccess: 28, waterAccess: 25,
    hazardScore: 97, riskLevel: 'CRITICAL', priorityScore: 99, priorityLevel: 'URGENT',
  },
  {
    name: 'Kaziranga Lowland Fringe',
    regionName: 'Assam',
    location: { type: 'Point', coordinates: [93.410, 26.580] },
    elevation: 78,
    population: 3900,
    children: 980, elderly: 540, disabled: 125, lowIncome: 2000, pregnantWomen: 75,
    floodRisk: 96, landslideRisk: 15, cycloneRisk: 28, heatRisk: 42, infrastructureRisk: 90,
    roadAccessibility: 22, healthcareAccess: 24, educationAccess: 32, waterAccess: 30,
    hazardScore: 93, riskLevel: 'CRITICAL', priorityScore: 96, priorityLevel: 'URGENT',
  },
  {
    name: 'Dhemaji Brahmaputra Basin',
    regionName: 'Assam',
    location: { type: 'Point', coordinates: [94.580, 27.480] },
    elevation: 92,
    population: 5400,
    children: 1380, elderly: 760, disabled: 180, lowIncome: 2800, pregnantWomen: 105,
    floodRisk: 97, landslideRisk: 20, cycloneRisk: 25, heatRisk: 38, infrastructureRisk: 92,
    roadAccessibility: 18, healthcareAccess: 22, educationAccess: 30, waterAccess: 28,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Silchar Barak Valley Ward',
    regionName: 'Assam',
    location: { type: 'Point', coordinates: [92.790, 24.830] },
    elevation: 32,
    population: 6200,
    children: 1550, elderly: 870, disabled: 210, lowIncome: 3100, pregnantWomen: 120,
    floodRisk: 95, landslideRisk: 62, cycloneRisk: 35, heatRisk: 45, infrastructureRisk: 88,
    roadAccessibility: 25, healthcareAccess: 32, educationAccess: 40, waterAccess: 32,
    hazardScore: 91, riskLevel: 'CRITICAL', priorityScore: 94, priorityLevel: 'URGENT',
  },
  {
    name: 'Barpeta Floodplain Village',
    regionName: 'Assam',
    location: { type: 'Point', coordinates: [91.000, 26.320] },
    elevation: 48,
    population: 4700,
    children: 1180, elderly: 650, disabled: 150, lowIncome: 2400, pregnantWomen: 88,
    floodRisk: 92, landslideRisk: 10, cycloneRisk: 30, heatRisk: 40, infrastructureRisk: 82,
    roadAccessibility: 28, healthcareAccess: 30, educationAccess: 38, waterAccess: 35,
    hazardScore: 85, riskLevel: 'HIGH', priorityScore: 88, priorityLevel: 'HIGH',
  },

  // UTTARAKHAND
  {
    name: 'Joshimath Subsidence Ward',
    regionName: 'Uttarakhand',
    location: { type: 'Point', coordinates: [79.565, 30.558] },
    elevation: 1890,
    population: 3200,
    children: 750, elderly: 480, disabled: 105, lowIncome: 1450, pregnantWomen: 55,
    floodRisk: 82, landslideRisk: 99, cycloneRisk: 10, heatRisk: 15, infrastructureRisk: 98,
    roadAccessibility: 15, healthcareAccess: 22, educationAccess: 30, waterAccess: 25,
    hazardScore: 98, riskLevel: 'CRITICAL', priorityScore: 99, priorityLevel: 'URGENT',
  },
  {
    name: 'Chamoli Alaknanda Gorge',
    regionName: 'Uttarakhand',
    location: { type: 'Point', coordinates: [79.350, 30.410] },
    elevation: 1150,
    population: 2900,
    children: 680, elderly: 430, disabled: 95, lowIncome: 1350, pregnantWomen: 48,
    floodRisk: 92, landslideRisk: 96, cycloneRisk: 10, heatRisk: 18, infrastructureRisk: 94,
    roadAccessibility: 18, healthcareAccess: 24, educationAccess: 32, waterAccess: 30,
    hazardScore: 95, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },
  {
    name: 'Kedarnath Valley Approach',
    regionName: 'Uttarakhand',
    location: { type: 'Point', coordinates: [79.060, 30.730] },
    elevation: 2450,
    population: 2100,
    children: 460, elderly: 310, disabled: 68, lowIncome: 950, pregnantWomen: 32,
    floodRisk: 95, landslideRisk: 95, cycloneRisk: 8, heatRisk: 12, infrastructureRisk: 96,
    roadAccessibility: 12, healthcareAccess: 15, educationAccess: 20, waterAccess: 25,
    hazardScore: 96, riskLevel: 'CRITICAL', priorityScore: 99, priorityLevel: 'URGENT',
  },
  {
    name: 'Uttarkashi Bhagirathi Slope',
    regionName: 'Uttarakhand',
    location: { type: 'Point', coordinates: [78.440, 30.730] },
    elevation: 1160,
    population: 3600,
    children: 840, elderly: 530, disabled: 118, lowIncome: 1680, pregnantWomen: 60,
    floodRisk: 86, landslideRisk: 93, cycloneRisk: 10, heatRisk: 20, infrastructureRisk: 90,
    roadAccessibility: 22, healthcareAccess: 28, educationAccess: 35, waterAccess: 32,
    hazardScore: 90, riskLevel: 'CRITICAL', priorityScore: 94, priorityLevel: 'URGENT',
  },
  {
    name: 'Rishikesh Lowland Ghat',
    regionName: 'Uttarakhand',
    location: { type: 'Point', coordinates: [78.290, 30.080] },
    elevation: 340,
    population: 6800,
    children: 1600, elderly: 980, disabled: 220, lowIncome: 3100, pregnantWomen: 115,
    floodRisk: 82, landslideRisk: 40, cycloneRisk: 20, heatRisk: 42, infrastructureRisk: 68,
    roadAccessibility: 48, healthcareAccess: 52, educationAccess: 58, waterAccess: 52,
    hazardScore: 74, riskLevel: 'HIGH', priorityScore: 77, priorityLevel: 'HIGH',
  },

  // MAHARASHTRA
  {
    name: 'Chiplun Vashishti Floodplain',
    regionName: 'Maharashtra',
    location: { type: 'Point', coordinates: [73.520, 17.530] },
    elevation: 18,
    population: 7800,
    children: 1950, elderly: 1150, disabled: 260, lowIncome: 3800, pregnantWomen: 140,
    floodRisk: 98, landslideRisk: 76, cycloneRisk: 72, heatRisk: 55, infrastructureRisk: 94,
    roadAccessibility: 22, healthcareAccess: 28, educationAccess: 38, waterAccess: 30,
    hazardScore: 96, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },
  {
    name: 'Mahad Savitri River Delta',
    regionName: 'Maharashtra',
    location: { type: 'Point', coordinates: [73.420, 18.080] },
    elevation: 16,
    population: 6400,
    children: 1580, elderly: 940, disabled: 210, lowIncome: 3100, pregnantWomen: 115,
    floodRisk: 96, landslideRisk: 82, cycloneRisk: 70, heatRisk: 52, infrastructureRisk: 92,
    roadAccessibility: 25, healthcareAccess: 30, educationAccess: 40, waterAccess: 32,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Mumbai Mithi River Kranti Nagar',
    regionName: 'Maharashtra',
    location: { type: 'Point', coordinates: [72.880, 19.070] },
    elevation: 4,
    population: 12500,
    children: 3200, elderly: 1600, disabled: 420, lowIncome: 7500, pregnantWomen: 260,
    floodRisk: 97, landslideRisk: 10, cycloneRisk: 80, heatRisk: 68, infrastructureRisk: 90,
    roadAccessibility: 30, healthcareAccess: 40, educationAccess: 45, waterAccess: 30,
    hazardScore: 93, riskLevel: 'CRITICAL', priorityScore: 96, priorityLevel: 'URGENT',
  },
  {
    name: 'Kolhapur Panchganga Lowland',
    regionName: 'Maharashtra',
    location: { type: 'Point', coordinates: [74.240, 16.700] },
    elevation: 545,
    population: 8100,
    children: 1980, elderly: 1180, disabled: 270, lowIncome: 3900, pregnantWomen: 150,
    floodRisk: 94, landslideRisk: 30, cycloneRisk: 45, heatRisk: 58, infrastructureRisk: 84,
    roadAccessibility: 32, healthcareAccess: 38, educationAccess: 48, waterAccess: 38,
    hazardScore: 88, riskLevel: 'CRITICAL', priorityScore: 92, priorityLevel: 'URGENT',
  },
  {
    name: 'Raigad Irshalwadi Foot',
    regionName: 'Maharashtra',
    location: { type: 'Point', coordinates: [73.230, 18.910] },
    elevation: 320,
    population: 1800,
    children: 420, elderly: 260, disabled: 58, lowIncome: 950, pregnantWomen: 32,
    floodRisk: 65, landslideRisk: 98, cycloneRisk: 50, heatRisk: 45, infrastructureRisk: 96,
    roadAccessibility: 12, healthcareAccess: 15, educationAccess: 22, waterAccess: 25,
    hazardScore: 95, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },

  // GUJARAT
  {
    name: 'Kutch Coastal Kandla Mudflats',
    regionName: 'Gujarat',
    location: { type: 'Point', coordinates: [70.220, 23.010] },
    elevation: 3,
    population: 5900,
    children: 1450, elderly: 780, disabled: 195, lowIncome: 3100, pregnantWomen: 110,
    floodRisk: 88, landslideRisk: 5, cycloneRisk: 98, heatRisk: 82, infrastructureRisk: 92,
    roadAccessibility: 25, healthcareAccess: 28, educationAccess: 35, waterAccess: 25,
    hazardScore: 95, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Morbi Machchhu Basin',
    regionName: 'Gujarat',
    location: { type: 'Point', coordinates: [70.830, 22.820] },
    elevation: 52,
    population: 6500,
    children: 1580, elderly: 890, disabled: 215, lowIncome: 3300, pregnantWomen: 120,
    floodRisk: 95, landslideRisk: 5, cycloneRisk: 72, heatRisk: 80, infrastructureRisk: 88,
    roadAccessibility: 30, healthcareAccess: 35, educationAccess: 42, waterAccess: 32,
    hazardScore: 91, riskLevel: 'CRITICAL', priorityScore: 94, priorityLevel: 'URGENT',
  },
  {
    name: 'Surat Tapi River Diwalibaug',
    regionName: 'Gujarat',
    location: { type: 'Point', coordinates: [72.830, 21.170] },
    elevation: 12,
    population: 11200,
    children: 2800, elderly: 1450, disabled: 370, lowIncome: 5800, pregnantWomen: 220,
    floodRisk: 94, landslideRisk: 5, cycloneRisk: 82, heatRisk: 75, infrastructureRisk: 86,
    roadAccessibility: 35, healthcareAccess: 42, educationAccess: 50, waterAccess: 38,
    hazardScore: 89, riskLevel: 'CRITICAL', priorityScore: 93, priorityLevel: 'URGENT',
  },

  // TAMIL NADU
  {
    name: 'Chennai Velachery Lowland',
    regionName: 'Tamil Nadu',
    location: { type: 'Point', coordinates: [80.220, 12.980] },
    elevation: 5,
    population: 14000,
    children: 3400, elderly: 1850, disabled: 460, lowIncome: 6800, pregnantWomen: 280,
    floodRisk: 98, landslideRisk: 5, cycloneRisk: 92, heatRisk: 75, infrastructureRisk: 92,
    roadAccessibility: 28, healthcareAccess: 38, educationAccess: 48, waterAccess: 32,
    hazardScore: 95, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Cuddalore Pennaiyar River Mouth',
    regionName: 'Tamil Nadu',
    location: { type: 'Point', coordinates: [79.770, 11.750] },
    elevation: 4,
    population: 6700,
    children: 1680, elderly: 920, disabled: 225, lowIncome: 3400, pregnantWomen: 125,
    floodRisk: 94, landslideRisk: 5, cycloneRisk: 98, heatRisk: 72, infrastructureRisk: 90,
    roadAccessibility: 25, healthcareAccess: 30, educationAccess: 38, waterAccess: 30,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Nagapattinam Delta Fishery Ward',
    regionName: 'Tamil Nadu',
    location: { type: 'Point', coordinates: [79.840, 10.770] },
    elevation: 3,
    population: 5800,
    children: 1450, elderly: 790, disabled: 195, lowIncome: 2950, pregnantWomen: 110,
    floodRisk: 92, landslideRisk: 5, cycloneRisk: 97, heatRisk: 70, infrastructureRisk: 88,
    roadAccessibility: 26, healthcareAccess: 30, educationAccess: 38, waterAccess: 32,
    hazardScore: 93, riskLevel: 'CRITICAL', priorityScore: 96, priorityLevel: 'URGENT',
  },

  // BIHAR
  {
    name: 'Supaul Kosi Embankment Hamlet',
    regionName: 'Bihar',
    location: { type: 'Point', coordinates: [86.600, 26.120] },
    elevation: 58,
    population: 5400,
    children: 1450, elderly: 720, disabled: 190, lowIncome: 3200, pregnantWomen: 115,
    floodRisk: 99, landslideRisk: 5, cycloneRisk: 25, heatRisk: 68, infrastructureRisk: 95,
    roadAccessibility: 15, healthcareAccess: 18, educationAccess: 25, waterAccess: 22,
    hazardScore: 97, riskLevel: 'CRITICAL', priorityScore: 99, priorityLevel: 'URGENT',
  },
  {
    name: 'Katihar Mahananda Basin',
    regionName: 'Bihar',
    location: { type: 'Point', coordinates: [87.580, 25.540] },
    elevation: 31,
    population: 6800,
    children: 1780, elderly: 920, disabled: 235, lowIncome: 3900, pregnantWomen: 140,
    floodRisk: 97, landslideRisk: 5, cycloneRisk: 28, heatRisk: 65, infrastructureRisk: 92,
    roadAccessibility: 18, healthcareAccess: 22, educationAccess: 28, waterAccess: 25,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Darbhanga Kamla Basin',
    regionName: 'Bihar',
    location: { type: 'Point', coordinates: [85.900, 26.150] },
    elevation: 49,
    population: 7200,
    children: 1900, elderly: 980, disabled: 250, lowIncome: 4100, pregnantWomen: 150,
    floodRisk: 95, landslideRisk: 5, cycloneRisk: 22, heatRisk: 68, infrastructureRisk: 90,
    roadAccessibility: 22, healthcareAccess: 25, educationAccess: 32, waterAccess: 28,
    hazardScore: 92, riskLevel: 'CRITICAL', priorityScore: 95, priorityLevel: 'URGENT',
  },

  // WEST BENGAL
  {
    name: 'Sundarbans Gosaba Island Hamlet',
    regionName: 'West Bengal',
    location: { type: 'Point', coordinates: [88.800, 22.160] },
    elevation: 2,
    population: 6200,
    children: 1620, elderly: 840, disabled: 215, lowIncome: 3600, pregnantWomen: 125,
    floodRisk: 96, landslideRisk: 5, cycloneRisk: 99, heatRisk: 65, infrastructureRisk: 95,
    roadAccessibility: 14, healthcareAccess: 18, educationAccess: 26, waterAccess: 22,
    hazardScore: 97, riskLevel: 'CRITICAL', priorityScore: 99, priorityLevel: 'URGENT',
  },
  {
    name: 'Sagar Island South Point',
    regionName: 'West Bengal',
    location: { type: 'Point', coordinates: [88.080, 21.650] },
    elevation: 3,
    population: 5400,
    children: 1380, elderly: 720, disabled: 185, lowIncome: 3100, pregnantWomen: 110,
    floodRisk: 95, landslideRisk: 5, cycloneRisk: 98, heatRisk: 64, infrastructureRisk: 94,
    roadAccessibility: 16, healthcareAccess: 20, educationAccess: 28, waterAccess: 24,
    hazardScore: 96, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },
  {
    name: 'Kakdwip Coastal Ward',
    regionName: 'West Bengal',
    location: { type: 'Point', coordinates: [88.180, 21.870] },
    elevation: 4,
    population: 7100,
    children: 1800, elderly: 960, disabled: 245, lowIncome: 4100, pregnantWomen: 145,
    floodRisk: 91, landslideRisk: 5, cycloneRisk: 96, heatRisk: 66, infrastructureRisk: 90,
    roadAccessibility: 22, healthcareAccess: 26, educationAccess: 35, waterAccess: 28,
    hazardScore: 93, riskLevel: 'CRITICAL', priorityScore: 96, priorityLevel: 'URGENT',
  },

  // ANDHRA PRADESH
  {
    name: 'Visakhapatnam Coastal Fishery Slum',
    regionName: 'Andhra Pradesh',
    location: { type: 'Point', coordinates: [83.300, 17.700] },
    elevation: 4,
    population: 7400,
    children: 1880, elderly: 980, disabled: 250, lowIncome: 4100, pregnantWomen: 148,
    floodRisk: 86, landslideRisk: 20, cycloneRisk: 98, heatRisk: 72, infrastructureRisk: 92,
    roadAccessibility: 24, healthcareAccess: 32, educationAccess: 40, waterAccess: 28,
    hazardScore: 95, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Machilipatnam Krishna Delta',
    regionName: 'Andhra Pradesh',
    location: { type: 'Point', coordinates: [81.130, 16.180] },
    elevation: 3,
    population: 6600,
    children: 1650, elderly: 890, disabled: 225, lowIncome: 3600, pregnantWomen: 130,
    floodRisk: 94, landslideRisk: 5, cycloneRisk: 98, heatRisk: 75, infrastructureRisk: 90,
    roadAccessibility: 22, healthcareAccess: 28, educationAccess: 36, waterAccess: 28,
    hazardScore: 95, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Vijayawada Krishna Floodplain',
    regionName: 'Andhra Pradesh',
    location: { type: 'Point', coordinates: [80.640, 16.510] },
    elevation: 18,
    population: 9200,
    children: 2300, elderly: 1240, disabled: 310, lowIncome: 4900, pregnantWomen: 185,
    floodRisk: 95, landslideRisk: 10, cycloneRisk: 80, heatRisk: 84, infrastructureRisk: 86,
    roadAccessibility: 30, healthcareAccess: 38, educationAccess: 46, waterAccess: 35,
    hazardScore: 91, riskLevel: 'CRITICAL', priorityScore: 94, priorityLevel: 'URGENT',
  },

  // RAJASTHAN
  {
    name: 'Barmer Thar Arid Settlement',
    regionName: 'Rajasthan',
    location: { type: 'Point', coordinates: [71.380, 25.750] },
    elevation: 220,
    population: 4200,
    children: 1100, elderly: 580, disabled: 140, lowIncome: 2350, pregnantWomen: 85,
    floodRisk: 10, landslideRisk: 5, cycloneRisk: 15, heatRisk: 99, infrastructureRisk: 94,
    roadAccessibility: 18, healthcareAccess: 20, educationAccess: 28, waterAccess: 12,
    hazardScore: 96, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },
  {
    name: 'Jaisalmer Dune Perimeter Hamlet',
    regionName: 'Rajasthan',
    location: { type: 'Point', coordinates: [70.920, 26.920] },
    elevation: 225,
    population: 3500,
    children: 920, elderly: 480, disabled: 115, lowIncome: 1950, pregnantWomen: 70,
    floodRisk: 8, landslideRisk: 5, cycloneRisk: 12, heatRisk: 98, infrastructureRisk: 92,
    roadAccessibility: 16, healthcareAccess: 18, educationAccess: 25, waterAccess: 14,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Churu Extreme Heat Core Ward',
    regionName: 'Rajasthan',
    location: { type: 'Point', coordinates: [74.960, 28.300] },
    elevation: 286,
    population: 5600,
    children: 1450, elderly: 780, disabled: 190, lowIncome: 3050, pregnantWomen: 112,
    floodRisk: 12, landslideRisk: 5, cycloneRisk: 15, heatRisk: 99, infrastructureRisk: 88,
    roadAccessibility: 28, healthcareAccess: 30, educationAccess: 38, waterAccess: 20,
    hazardScore: 91, riskLevel: 'CRITICAL', priorityScore: 94, priorityLevel: 'URGENT',
  },

  // DELHI NCR
  {
    name: 'Yamuna Khadar Floodplain Slum',
    regionName: 'Delhi NCR',
    location: { type: 'Point', coordinates: [77.260, 28.620] },
    elevation: 205,
    population: 11500,
    children: 2950, elderly: 1450, disabled: 380, lowIncome: 7100, pregnantWomen: 235,
    floodRisk: 98, landslideRisk: 5, cycloneRisk: 20, heatRisk: 88, infrastructureRisk: 94,
    roadAccessibility: 20, healthcareAccess: 28, educationAccess: 35, waterAccess: 25,
    hazardScore: 96, riskLevel: 'CRITICAL', priorityScore: 98, priorityLevel: 'URGENT',
  },
  {
    name: 'Kashmiri Gate Riverbed Ward',
    regionName: 'Delhi NCR',
    location: { type: 'Point', coordinates: [77.230, 28.660] },
    elevation: 208,
    population: 7800,
    children: 1980, elderly: 1020, disabled: 260, lowIncome: 4600, pregnantWomen: 155,
    floodRisk: 94, landslideRisk: 5, cycloneRisk: 18, heatRisk: 86, infrastructureRisk: 90,
    roadAccessibility: 25, healthcareAccess: 32, educationAccess: 40, waterAccess: 30,
    hazardScore: 92, riskLevel: 'CRITICAL', priorityScore: 95, priorityLevel: 'URGENT',
  },
  {
    name: 'East Delhi Mayur Vihar Lowland',
    regionName: 'Delhi NCR',
    location: { type: 'Point', coordinates: [77.290, 28.600] },
    elevation: 206,
    population: 9200,
    children: 2300, elderly: 1200, disabled: 305, lowIncome: 5200, pregnantWomen: 180,
    floodRisk: 89, landslideRisk: 5, cycloneRisk: 22, heatRisk: 90, infrastructureRisk: 82,
    roadAccessibility: 35, healthcareAccess: 40, educationAccess: 48, waterAccess: 35,
    hazardScore: 86, riskLevel: 'HIGH', priorityScore: 89, priorityLevel: 'HIGH',
  },

  // KARNATAKA
  {
    name: 'Kodagu Madikeri Slope Ward',
    regionName: 'Karnataka',
    location: { type: 'Point', coordinates: [75.740, 12.420] },
    elevation: 1150,
    population: 4600,
    children: 1100, elderly: 620, disabled: 150, lowIncome: 2200, pregnantWomen: 90,
    floodRisk: 82, landslideRisk: 97, cycloneRisk: 45, heatRisk: 30, infrastructureRisk: 92,
    roadAccessibility: 22, healthcareAccess: 28, educationAccess: 36, waterAccess: 38,
    hazardScore: 94, riskLevel: 'CRITICAL', priorityScore: 97, priorityLevel: 'URGENT',
  },
  {
    name: 'Karwar Kali Estuary Village',
    regionName: 'Karnataka',
    location: { type: 'Point', coordinates: [74.130, 14.810] },
    elevation: 5,
    population: 5200,
    children: 1280, elderly: 710, disabled: 175, lowIncome: 2600, pregnantWomen: 105,
    floodRisk: 94, landslideRisk: 40, cycloneRisk: 80, heatRisk: 48, infrastructureRisk: 88,
    roadAccessibility: 26, healthcareAccess: 30, educationAccess: 40, waterAccess: 32,
    hazardScore: 91, riskLevel: 'CRITICAL', priorityScore: 94, priorityLevel: 'URGENT',
  },
  {
    name: 'Udupi Swarna Floodplain',
    regionName: 'Karnataka',
    location: { type: 'Point', coordinates: [74.750, 13.340] },
    elevation: 8,
    population: 6100,
    children: 1480, elderly: 820, disabled: 200, lowIncome: 2950, pregnantWomen: 120,
    floodRisk: 88, landslideRisk: 25, cycloneRisk: 72, heatRisk: 50, infrastructureRisk: 78,
    roadAccessibility: 34, healthcareAccess: 40, educationAccess: 48, waterAccess: 42,
    hazardScore: 82, riskLevel: 'HIGH', priorityScore: 85, priorityLevel: 'HIGH',
  },
];

export const allSafeSitesData = [
  ...telanganaSafeSites,

  // KERALA
  {
    name: 'Sulthan Bathery High Ridge',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.255, 11.660] },
    elevation: 930,
    totalCapacity: 8500, occupiedCapacity: 1200,
    waterCapacity: 85, healthcareScore: 82, educationScore: 80, roadAccessibility: 88,
    infrastructureScore: 86, landAvailability: 84, hazardScore: 12, transportDistance: 22,
    transportCost: 350, safetyScore: 88, carryingCapacityScore: 85, overallSafetyScore: 87,
    description: 'Elevated bedrock plateau with dedicated power grid, storage shelters, and direct NH connectivity',
    amenities: ['24/7 Water Filtration', 'Medical Camp', 'Solar Power Backup', 'Helipad Access', 'Community Kitchen'],
  },
  {
    name: 'Kalpetta Highland Resettlement',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.085, 11.610] },
    elevation: 880,
    totalCapacity: 12000, occupiedCapacity: 2400,
    waterCapacity: 90, healthcareScore: 88, educationScore: 85, roadAccessibility: 92,
    infrastructureScore: 90, landAvailability: 88, hazardScore: 10, transportDistance: 18,
    transportCost: 300, safetyScore: 90, carryingCapacityScore: 89, overallSafetyScore: 90,
    description: 'District headquarters designated safe zone with high-capacity shelter warehouses and hospital proximity',
    amenities: ['General Hospital Access', 'Mass Feeding Kitchen', 'Communications Tower', 'Schools for Housing'],
  },
  {
    name: 'Thodupuzha Elevated Zone',
    regionName: 'Kerala',
    location: { type: 'Point', coordinates: [76.715, 9.895] },
    elevation: 65,
    totalCapacity: 9000, occupiedCapacity: 1100,
    waterCapacity: 82, healthcareScore: 80, educationScore: 82, roadAccessibility: 85,
    infrastructureScore: 84, landAvailability: 80, hazardScore: 14, transportDistance: 28,
    transportCost: 420, safetyScore: 86, carryingCapacityScore: 83, overallSafetyScore: 85,
    description: 'Stable foothills host zone serving Idukki and Kottayam displaced communities',
    amenities: ['Tubewell Water', 'Primary Health Center', 'Shelter Sheds', 'All-Weather Highway'],
  },

  // ODISHA
  {
    name: 'Bhubaneswar Elevated Shelter Hub',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [85.820, 20.300] },
    elevation: 45,
    totalCapacity: 16000, occupiedCapacity: 3500,
    waterCapacity: 92, healthcareScore: 95, educationScore: 90, roadAccessibility: 96,
    infrastructureScore: 94, landAvailability: 90, hazardScore: 8, transportDistance: 45,
    transportCost: 550, safetyScore: 92, carryingCapacityScore: 93, overallSafetyScore: 93,
    description: 'Capital mega-evacuation complex with multi-tier emergency shelters and AIIMS proximity',
    amenities: ['Multi-Specialty Hospital', 'Central Food Depot', 'Air Strip Access', 'Generator Substations'],
  },
  {
    name: 'Khordha Highland Safe Zone',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [85.620, 20.180] },
    elevation: 68,
    totalCapacity: 14000, occupiedCapacity: 2100,
    waterCapacity: 88, healthcareScore: 84, educationScore: 86, roadAccessibility: 90,
    infrastructureScore: 88, landAvailability: 92, hazardScore: 10, transportDistance: 50,
    transportCost: 600, safetyScore: 90, carryingCapacityScore: 90, overallSafetyScore: 90,
    description: 'Cyclone-resilient hill complex serving Puri and coastal delta evacuees',
    amenities: ['Cyclone Shelter Buildings', 'Filtered Water Tanks', 'Ambulance Station', 'Community Radio'],
  },
  {
    name: 'Dhenkanal Ridge Base',
    regionName: 'Odisha',
    location: { type: 'Point', coordinates: [85.590, 20.660] },
    elevation: 110,
    totalCapacity: 11000, occupiedCapacity: 1500,
    waterCapacity: 84, healthcareScore: 80, educationScore: 82, roadAccessibility: 86,
    infrastructureScore: 85, landAvailability: 88, hazardScore: 12, transportDistance: 65,
    transportCost: 750, safetyScore: 88, carryingCapacityScore: 86, overallSafetyScore: 87,
    description: 'Inland high ridge providing complete flood and storm surge immunity',
    amenities: ['High-Volume Water Storage', 'Mobile Health Units', 'Warehouses', 'Reinforced Shelters'],
  },

  // ASSAM
  {
    name: 'Guwahati Khanapara High Plateau',
    regionName: 'Assam',
    location: { type: 'Point', coordinates: [91.820, 26.110] },
    elevation: 140,
    totalCapacity: 18000, occupiedCapacity: 4000,
    waterCapacity: 92, healthcareScore: 94, educationScore: 92, roadAccessibility: 94,
    infrastructureScore: 93, landAvailability: 88, hazardScore: 8, transportDistance: 35,
    transportCost: 480, safetyScore: 92, carryingCapacityScore: 92, overallSafetyScore: 92,
    description: 'Elevated foothill mega-facility outside Brahmaputra flood line with major hospital connectivity',
    amenities: ['GMC Hospital Access', 'Mass Evacuation Halls', 'Helipad', 'Central Relief Stockpile'],
  },
  {
    name: 'Tezpur Elevated Safe Base',
    regionName: 'Assam',
    location: { type: 'Point', coordinates: [92.800, 26.650] },
    elevation: 95,
    totalCapacity: 12500, occupiedCapacity: 2200,
    waterCapacity: 86, healthcareScore: 85, educationScore: 84, roadAccessibility: 88,
    infrastructureScore: 87, landAvailability: 86, hazardScore: 10, transportDistance: 45,
    transportCost: 550, safetyScore: 90, carryingCapacityScore: 88, overallSafetyScore: 89,
    description: 'Military and civil coordinated highland base serving Sonitpur and Kaziranga evacuees',
    amenities: ['Army Logistics Support', 'Clean Water Plant', 'Medical Camp', 'Permanent Barracks'],
  },

  // UTTARAKHAND
  {
    name: 'Dehradun Valley Resettlement Hub',
    regionName: 'Uttarakhand',
    location: { type: 'Point', coordinates: [78.030, 30.320] },
    elevation: 640,
    totalCapacity: 20000, occupiedCapacity: 3800,
    waterCapacity: 94, healthcareScore: 96, educationScore: 92, roadAccessibility: 96,
    infrastructureScore: 95, landAvailability: 90, hazardScore: 8, transportDistance: 95,
    transportCost: 950, safetyScore: 92, carryingCapacityScore: 93, overallSafetyScore: 93,
    description: 'State central emergency response base outside active Himalayan fault zones',
    amenities: ['All-India Hospital Access', 'Modular Pre-Fab Housing', 'Central Relief Depot', 'Helipad'],
  },
  {
    name: 'Srinagar Garhwal Safe Terrace',
    regionName: 'Uttarakhand',
    location: { type: 'Point', coordinates: [78.780, 30.220] },
    elevation: 560,
    totalCapacity: 11000, occupiedCapacity: 2100,
    waterCapacity: 88, healthcareScore: 86, educationScore: 85, roadAccessibility: 88,
    infrastructureScore: 87, landAvailability: 85, hazardScore: 12, transportDistance: 55,
    transportCost: 650, safetyScore: 88, carryingCapacityScore: 87, overallSafetyScore: 88,
    description: 'Elevated river terrace with medical college access for Garhwal landslide evacuees',
    amenities: ['Medical College Hospital', 'Reinforced Evacuation Halls', 'Clean Spring Water', 'NH Connectivity'],
  },

  // MAHARASHTRA
  {
    name: 'Pune Kothrud High Ground',
    regionName: 'Maharashtra',
    location: { type: 'Point', coordinates: [73.810, 18.510] },
    elevation: 580,
    totalCapacity: 25000, occupiedCapacity: 6000,
    waterCapacity: 95, healthcareScore: 96, educationScore: 95, roadAccessibility: 98,
    infrastructureScore: 96, landAvailability: 92, hazardScore: 6, transportDistance: 120,
    transportCost: 1100, safetyScore: 94, carryingCapacityScore: 95, overallSafetyScore: 95,
    description: 'Deccan plateau mega safe zone with comprehensive civic infrastructure and transport links',
    amenities: ['Super Specialty Hospitals', 'Expressway Transit Hub', 'Mass Housing Hostels', 'Power Substation'],
  },
  {
    name: 'Satara Plateau Safe Zone',
    regionName: 'Maharashtra',
    location: { type: 'Point', coordinates: [73.990, 17.690] },
    elevation: 740,
    totalCapacity: 16000, occupiedCapacity: 2800,
    waterCapacity: 90, healthcareScore: 86, educationScore: 88, roadAccessibility: 90,
    infrastructureScore: 89, landAvailability: 92, hazardScore: 8, transportDistance: 65,
    transportCost: 680, safetyScore: 92, carryingCapacityScore: 90, overallSafetyScore: 91,
    description: 'High-elevation tableland serving Chiplun, Mahad, and Konkan valley populations',
    amenities: ['District Hospital', 'Water Purification Reservoirs', 'Highway Staging Area', 'Storage Godowns'],
  },

  // GUJARAT
  {
    name: 'Rajkot Elevated Resettlement Zone',
    regionName: 'Gujarat',
    location: { type: 'Point', coordinates: [70.800, 22.300] },
    elevation: 135,
    totalCapacity: 18000, occupiedCapacity: 3500,
    waterCapacity: 90, healthcareScore: 92, educationScore: 90, roadAccessibility: 94,
    infrastructureScore: 93, landAvailability: 92, hazardScore: 8, transportDistance: 85,
    transportCost: 820, safetyScore: 92, carryingCapacityScore: 92, overallSafetyScore: 92,
    description: 'Saurashtra central highland hub providing complete cyclone storm surge immunity',
    amenities: ['Civil Hospital', 'Solar Power Backups', 'Water Tanker Terminals', 'Evacuation Centers'],
  },

  // TAMIL NADU
  {
    name: 'Chengalpattu Elevated Plateau',
    regionName: 'Tamil Nadu',
    location: { type: 'Point', coordinates: [79.980, 12.680] },
    elevation: 48,
    totalCapacity: 20000, occupiedCapacity: 4200,
    waterCapacity: 92, healthcareScore: 94, educationScore: 90, roadAccessibility: 96,
    infrastructureScore: 94, landAvailability: 90, hazardScore: 8, transportDistance: 45,
    transportCost: 520, safetyScore: 92, carryingCapacityScore: 93, overallSafetyScore: 93,
    description: 'Southern Chennai outer highland hub outside coastal storm and river flood plains',
    amenities: ['Government Medical College', 'Suburban Rail Transit', 'Water Reservoirs', 'Modular Shelters'],
  },

  // BIHAR
  {
    name: 'Patna Bihta Safe Hub',
    regionName: 'Bihar',
    location: { type: 'Point', coordinates: [84.870, 25.560] },
    elevation: 62,
    totalCapacity: 22000, occupiedCapacity: 4500,
    waterCapacity: 90, healthcareScore: 92, educationScore: 88, roadAccessibility: 94,
    infrastructureScore: 92, landAvailability: 94, hazardScore: 8, transportDistance: 35,
    transportCost: 450, safetyScore: 92, carryingCapacityScore: 92, overallSafetyScore: 92,
    description: 'High-elevation western capital zone with Air Force base logistics and disaster shelters',
    amenities: ['ESIC Hospital Access', 'Air Base Cargo Runway', 'Water Purification Towers', 'Mega Sheds'],
  },

  // WEST BENGAL
  {
    name: 'Kolkata Rajarhat Safe Zone',
    regionName: 'West Bengal',
    location: { type: 'Point', coordinates: [88.460, 22.590] },
    elevation: 12,
    totalCapacity: 26000, occupiedCapacity: 5500,
    waterCapacity: 94, healthcareScore: 96, educationScore: 94, roadAccessibility: 96,
    infrastructureScore: 95, landAvailability: 92, hazardScore: 8, transportDistance: 65,
    transportCost: 700, safetyScore: 92, carryingCapacityScore: 94, overallSafetyScore: 93,
    description: 'Planned modern highland sector serving Sundarbans and southern coastal evacuees',
    amenities: ['Apex Hospitals', 'Metro Rail Connectivity', 'Relief Staging Warehouses', 'Power Grids'],
  },

  // ANDHRA PRADESH
  {
    name: 'Amaravati High Plateau Hub',
    regionName: 'Andhra Pradesh',
    location: { type: 'Point', coordinates: [80.520, 16.510] },
    elevation: 35,
    totalCapacity: 20000, occupiedCapacity: 3800,
    waterCapacity: 92, healthcareScore: 94, educationScore: 92, roadAccessibility: 96,
    infrastructureScore: 94, landAvailability: 95, hazardScore: 8, transportDistance: 25,
    transportCost: 350, safetyScore: 92, carryingCapacityScore: 93, overallSafetyScore: 93,
    description: 'Capital upland zone engineered above Krishna 100-year flood levels',
    amenities: ['AIIMS Mangalagiri Access', 'Multi-Lane Expressways', 'Water Treatment Plant', 'Mass Shelters'],
  },

  // RAJASTHAN
  {
    name: 'Jodhpur High Ground Safe Oasis',
    regionName: 'Rajasthan',
    location: { type: 'Point', coordinates: [73.020, 26.280] },
    elevation: 245,
    totalCapacity: 15000, occupiedCapacity: 2800,
    waterCapacity: 88, healthcareScore: 92, educationScore: 88, roadAccessibility: 94,
    infrastructureScore: 91, landAvailability: 90, hazardScore: 10, transportDistance: 85,
    transportCost: 850, safetyScore: 90, carryingCapacityScore: 90, overallSafetyScore: 90,
    description: 'Elevated sandstone plateau with canal water supply, cooling shelters, and AIIMS hospital',
    amenities: ['AIIMS Jodhpur', 'Air-Cooled Shelters', 'Indira Gandhi Canal Water', 'Power Stations'],
  },

  // DELHI NCR
  {
    name: 'Dwarka High Ground Resettlement',
    regionName: 'Delhi NCR',
    location: { type: 'Point', coordinates: [77.050, 28.580] },
    elevation: 222,
    totalCapacity: 25000, occupiedCapacity: 5500,
    waterCapacity: 95, healthcareScore: 96, educationScore: 94, roadAccessibility: 98,
    infrastructureScore: 96, landAvailability: 90, hazardScore: 6, transportDistance: 22,
    transportCost: 320, safetyScore: 94, carryingCapacityScore: 94, overallSafetyScore: 94,
    description: 'Planned sub-city plateau far from Yamuna floodplain with direct hospital and airport access',
    amenities: ['Indira Gandhi Hospital', 'Metro Rail Network', 'Underground Water Reservoirs', 'DDA Community Halls'],
  },

  // KARNATAKA
  {
    name: 'Mysore High Plateau Resettlement',
    regionName: 'Karnataka',
    location: { type: 'Point', coordinates: [76.640, 12.300] },
    elevation: 765,
    totalCapacity: 20000, occupiedCapacity: 3500,
    waterCapacity: 94, healthcareScore: 95, educationScore: 92, roadAccessibility: 96,
    infrastructureScore: 95, landAvailability: 92, hazardScore: 6, transportDistance: 95,
    transportCost: 920, safetyScore: 94, carryingCapacityScore: 94, overallSafetyScore: 94,
    description: 'Deccan plateau historical sanctuary outside Western Ghats landslide and coastal flood zones',
    amenities: ['Kalyan Hospitals', 'NH 275 Expressway', 'KRS Dam Filtered Water', 'City Convention Centers'],
  },
];

export const allHazardZonesData = [
  ...telanganaHazards,

  // KERALA HAZARDS
  {
    name: 'Wayanad Debris & Landslide Zone',
    type: 'landslide',
    severity: 'CRITICAL',
    riskScore: 98,
    regionName: 'Kerala',
    geometry: {
      type: 'Polygon',
      coordinates: [[[76.10, 11.50], [76.22, 11.50], [76.22, 11.60], [76.10, 11.60], [76.10, 11.50]]],
    },
    affectedPopulation: 14500,
    description: 'Critical Western Ghats high-gradient slope failure corridor prone to catastrophic monsoon debris flows',
  },
  {
    name: 'Kuttanad Below-Sea-Level Inundation',
    type: 'flood',
    severity: 'CRITICAL',
    riskScore: 95,
    regionName: 'Kerala',
    geometry: {
      type: 'Polygon',
      coordinates: [[[76.30, 9.35], [76.45, 9.35], [76.45, 9.55], [76.30, 9.55], [76.30, 9.35]]],
    },
    affectedPopulation: 22000,
    description: 'Low-lying delta basin 1 to 2 meters below sea level with perennial waterlogging and monsoon tidal surges',
  },

  // ODISHA HAZARDS
  {
    name: 'Bay of Bengal Super Cyclone Landfall Belt',
    type: 'cyclone',
    severity: 'CRITICAL',
    riskScore: 99,
    regionName: 'Odisha',
    geometry: {
      type: 'Polygon',
      coordinates: [[[85.60, 19.60], [86.80, 20.20], [87.10, 21.60], [86.50, 21.60], [85.60, 19.60]]],
    },
    affectedPopulation: 38000,
    description: 'High-frequency tropical cyclone track with severe storm surges (up to 5m) and wind speeds exceeding 200 km/h',
  },
  {
    name: 'Mahanadi Delta Flood Inundation Corridor',
    type: 'flood',
    severity: 'CRITICAL',
    riskScore: 92,
    regionName: 'Odisha',
    geometry: {
      type: 'Polygon',
      coordinates: [[[85.70, 20.30], [86.50, 20.30], [86.50, 20.70], [85.70, 20.70], [85.70, 20.30]]],
    },
    affectedPopulation: 28000,
    description: 'Mahanadi-Brahmani river confluence floodplain subject to catastrophic spillway release inundation',
  },

  // ASSAM HAZARDS
  {
    name: 'Brahmaputra Megaflood Corridor',
    type: 'flood',
    severity: 'CRITICAL',
    riskScore: 98,
    regionName: 'Assam',
    geometry: {
      type: 'Polygon',
      coordinates: [[[91.00, 26.00], [95.00, 27.50], [95.00, 27.80], [91.00, 26.50], [91.00, 26.00]]],
    },
    affectedPopulation: 45000,
    description: 'Massive annual riverine flood zone causing severe channel shifting, island submergence, and sediment deposition',
  },

  // UTTARAKHAND HAZARDS
  {
    name: 'Joshimath Active Land Subsidence Fault',
    type: 'landslide',
    severity: 'CRITICAL',
    riskScore: 99,
    regionName: 'Uttarakhand',
    geometry: {
      type: 'Polygon',
      coordinates: [[[79.50, 30.50], [79.62, 30.50], [79.62, 30.60], [79.50, 30.60], [79.50, 30.50]]],
    },
    affectedPopulation: 12000,
    description: 'Active tectonic land subsidence and moraine slope degradation threatening urban structures and mountain highways',
  },

  // MAHARASHTRA HAZARDS
  {
    name: 'Konkan River Basin Flash Flood Zone',
    type: 'flood',
    severity: 'CRITICAL',
    riskScore: 96,
    regionName: 'Maharashtra',
    geometry: {
      type: 'Polygon',
      coordinates: [[[73.30, 17.30], [73.70, 17.30], [73.70, 18.30], [73.30, 18.30], [73.30, 17.30]]],
    },
    affectedPopulation: 32000,
    description: 'Narrow coastal river catchments subject to rapid extreme rainfall pooling and high-tide drainage blockages',
  },

  // GUJARAT HAZARDS
  {
    name: 'Kutch Arabian Sea Cyclone Surge Zone',
    type: 'cyclone',
    severity: 'CRITICAL',
    riskScore: 97,
    regionName: 'Gujarat',
    geometry: {
      type: 'Polygon',
      coordinates: [[[69.40, 22.80], [70.50, 22.80], [70.50, 23.40], [69.40, 23.40], [69.40, 22.80]]],
    },
    affectedPopulation: 24000,
    description: 'Coastal mudflat and port zone vulnerable to severe cyclonic surges and low-gradient saltwater inundation',
  },

  // TAMIL NADU HAZARDS
  {
    name: 'Coromandel Coastal Cyclone Track',
    type: 'cyclone',
    severity: 'CRITICAL',
    riskScore: 96,
    regionName: 'Tamil Nadu',
    geometry: {
      type: 'Polygon',
      coordinates: [[[79.60, 10.50], [80.35, 13.20], [80.10, 13.20], [79.60, 10.50]]],
    },
    affectedPopulation: 35000,
    description: 'Northeast monsoon cyclonic landfall track producing urban deluge, coastal erosion, and drainage backflow',
  },

  // BIHAR HAZARDS
  {
    name: 'Kosi Shifting Channel Inundation Zone',
    type: 'flood',
    severity: 'CRITICAL',
    riskScore: 98,
    regionName: 'Bihar',
    geometry: {
      type: 'Polygon',
      coordinates: [[[85.80, 25.40], [87.60, 25.40], [87.60, 26.50], [85.80, 26.50], [85.80, 25.40]]],
    },
    affectedPopulation: 42000,
    description: 'Unstable shifting river course carrying high silt load causing widespread rural embankment breaches and water stagnation',
  },

  // WEST BENGAL HAZARDS
  {
    name: 'Sundarbans Estuarine Cyclone Surge Zone',
    type: 'cyclone',
    severity: 'CRITICAL',
    riskScore: 99,
    regionName: 'West Bengal',
    geometry: {
      type: 'Polygon',
      coordinates: [[[88.00, 21.50], [89.10, 21.50], [89.10, 22.40], [88.00, 22.40], [88.00, 21.50]]],
    },
    affectedPopulation: 36000,
    description: 'Mangrove delta island network facing severe saltwater dyke breaches, tidal surges, and chronic land loss',
  },

  // ANDHRA PRADESH HAZARDS
  {
    name: 'Krishna & Godavari Delta Cyclone Surge Belt',
    type: 'cyclone',
    severity: 'CRITICAL',
    riskScore: 97,
    regionName: 'Andhra Pradesh',
    geometry: {
      type: 'Polygon',
      coordinates: [[[80.40, 15.80], [82.50, 17.20], [82.10, 17.20], [80.40, 15.80]]],
    },
    affectedPopulation: 31000,
    description: 'Intense Bay of Bengal cyclone landfall zone with low coastal elevation and river flood confluence',
  },

  // RAJASTHAN HAZARDS
  {
    name: 'Thar Desert Extreme Heatwave Dome',
    type: 'heat',
    severity: 'CRITICAL',
    riskScore: 99,
    regionName: 'Rajasthan',
    geometry: {
      type: 'Polygon',
      coordinates: [[[70.50, 25.00], [75.50, 25.00], [75.50, 29.00], [70.50, 29.00], [70.50, 25.00]]],
    },
    affectedPopulation: 26000,
    description: 'Sustained hyperthermic zone with ground temperatures above 48°C, severe moisture deficit, and groundwater depletion',
  },

  // DELHI NCR HAZARDS
  {
    name: 'Yamuna River Overflow Basin',
    type: 'flood',
    severity: 'CRITICAL',
    riskScore: 96,
    regionName: 'Delhi NCR',
    geometry: {
      type: 'Polygon',
      coordinates: [[[77.20, 28.55], [77.32, 28.55], [77.32, 28.72], [77.20, 28.72], [77.20, 28.55]]],
    },
    affectedPopulation: 29000,
    description: 'Hathnikund barrage surge channel inundating dense urban floodplains, slums, and major transit corridors',
  },

  // KARNATAKA HAZARDS
  {
    name: 'Western Ghats Kodagu Landslide Corridor',
    type: 'landslide',
    severity: 'CRITICAL',
    riskScore: 96,
    regionName: 'Karnataka',
    geometry: {
      type: 'Polygon',
      coordinates: [[[75.50, 12.20], [76.00, 12.20], [76.00, 12.80], [75.50, 12.80], [75.50, 12.20]]],
    },
    affectedPopulation: 16000,
    description: 'Steep montane coffee plantation slopes prone to heavy monsoon saturation failures and road cut slips',
  },
];
