export const regionsData = [
  {
    name: 'All India',
    state: 'India',
    country: 'India',
    category: 'National',
    population: 1428000000,
    area: 3287263,
    center: { lat: 22.5937, lng: 78.9629 },
    bounds: { north: 35.5, south: 8.0, east: 97.0, west: 68.0 },
    defaultZoom: 5,
    description: 'National multi-hazard risk overview across all states and union territories',
  },
  {
    name: 'Telangana',
    state: 'Telangana',
    country: 'India',
    category: 'South India',
    population: 38500000,
    area: 112077,
    center: { lat: 17.85, lng: 79.10 },
    bounds: { north: 19.93, south: 15.73, east: 81.35, west: 77.19 },
    defaultZoom: 7,
    description: 'Krishna & Godavari river basins, summer heatwave corridors, and urban flash flood risks',
  },
  {
    name: 'Kerala',
    state: 'Kerala',
    country: 'India',
    category: 'South India',
    population: 35000000,
    area: 38863,
    center: { lat: 10.25, lng: 76.45 },
    bounds: { north: 12.8, south: 8.3, east: 77.4, west: 74.9 },
    defaultZoom: 8,
    description: 'Western Ghats debris flows, Wayanad & Idukki landslide hotspots, and Kuttanad delta floods',
  },
  {
    name: 'Odisha',
    state: 'Odisha',
    country: 'India',
    category: 'East & Coastal',
    population: 46000000,
    area: 155707,
    center: { lat: 20.30, lng: 85.80 },
    bounds: { north: 22.6, south: 17.8, east: 87.5, west: 81.4 },
    defaultZoom: 7,
    description: 'Bay of Bengal tropical cyclone landfall belt, coastal storm surges, and Mahanadi river floods',
  },
  {
    name: 'Assam',
    state: 'Assam',
    country: 'India',
    category: 'North East',
    population: 36000000,
    area: 78438,
    center: { lat: 26.20, lng: 92.90 },
    bounds: { north: 28.0, south: 24.1, east: 96.0, west: 89.7 },
    defaultZoom: 7,
    description: 'Brahmaputra & Barak annual riverine floods, Majuli island erosion, and highland flash floods',
  },
  {
    name: 'Uttarakhand',
    state: 'Uttarakhand',
    country: 'India',
    category: 'Himalayan & North',
    population: 11500000,
    area: 53483,
    center: { lat: 30.20, lng: 79.20 },
    bounds: { north: 31.5, south: 28.7, east: 81.1, west: 77.6 },
    defaultZoom: 8,
    description: 'Himalayan seismic belt, Joshimath land subsidence, cloudbursts, and flash flood gorges',
  },
  {
    name: 'Himachal Pradesh',
    state: 'Himachal Pradesh',
    country: 'India',
    category: 'Himalayan & North',
    population: 7500000,
    area: 55673,
    center: { lat: 31.85, lng: 77.15 },
    bounds: { north: 33.3, south: 30.4, east: 79.0, west: 75.6 },
    defaultZoom: 8,
    description: 'Beas & Sutlej valley flash floods, slope instability, and cloudburst events',
  },
  {
    name: 'Maharashtra',
    state: 'Maharashtra',
    country: 'India',
    category: 'West India',
    population: 125000000,
    area: 307713,
    center: { lat: 18.90, lng: 74.50 },
    bounds: { north: 22.0, south: 15.6, east: 80.9, west: 72.6 },
    defaultZoom: 7,
    description: 'Konkan coast monsoon surges, Chiplun/Mahad river basin floods, and Western Ghats landslides',
  },
  {
    name: 'Gujarat',
    state: 'Gujarat',
    country: 'India',
    category: 'West India',
    population: 70000000,
    area: 196024,
    center: { lat: 22.80, lng: 71.20 },
    bounds: { north: 24.7, south: 20.1, east: 74.5, west: 68.1 },
    defaultZoom: 7,
    description: 'Arabian Sea cyclone tracks, Kutch seismic/arid vulnerability, and Tapi/Narmada river floods',
  },
  {
    name: 'Tamil Nadu',
    state: 'Tamil Nadu',
    country: 'India',
    category: 'South India',
    population: 77000000,
    area: 130058,
    center: { lat: 11.12, lng: 78.65 },
    bounds: { north: 13.6, south: 8.1, east: 80.3, west: 76.2 },
    defaultZoom: 7,
    description: 'Northeast monsoon inundation, Coromandel coast cyclones, and Chennai urban drainage bottlenecks',
  },
  {
    name: 'Bihar',
    state: 'Bihar',
    country: 'India',
    category: 'East & Central',
    population: 128000000,
    area: 94163,
    center: { lat: 25.65, lng: 85.80 },
    bounds: { north: 27.5, south: 24.3, east: 88.3, west: 83.3 },
    defaultZoom: 7,
    description: 'Kosi ("Sorrow of Bihar") river shifts, Ganga/Gandak recurrent inundation, and rural isolation',
  },
  {
    name: 'West Bengal',
    state: 'West Bengal',
    country: 'India',
    category: 'East & Coastal',
    population: 99000000,
    area: 88752,
    center: { lat: 22.98, lng: 87.85 },
    bounds: { north: 27.2, south: 21.5, east: 89.9, west: 85.8 },
    defaultZoom: 7,
    description: 'Sundarbans delta storm surge erosion, Bay of Bengal super cyclones, and Teesta flash floods',
  },
  {
    name: 'Andhra Pradesh',
    state: 'Andhra Pradesh',
    country: 'India',
    category: 'South India',
    population: 53000000,
    area: 162968,
    center: { lat: 15.91, lng: 80.00 },
    bounds: { north: 19.1, south: 12.6, east: 84.8, west: 76.8 },
    defaultZoom: 7,
    description: 'Godavari & Krishna delta flooding, coastal storm surge vulnerability, and Rayalaseema heatwaves',
  },
  {
    name: 'Rajasthan',
    state: 'Rajasthan',
    country: 'India',
    category: 'West India',
    population: 81000000,
    area: 342239,
    center: { lat: 26.90, lng: 73.00 },
    bounds: { north: 30.2, south: 23.1, east: 78.3, west: 69.5 },
    defaultZoom: 7,
    description: 'Thar Desert extreme heat dome (48°C+), ground water depletion, and severe drought vulnerability',
  },
  {
    name: 'Delhi NCR',
    state: 'Delhi',
    country: 'India',
    category: 'Himalayan & North',
    population: 33000000,
    area: 1484,
    center: { lat: 28.61, lng: 77.20 },
    bounds: { north: 28.9, south: 28.4, east: 77.4, west: 76.9 },
    defaultZoom: 10,
    description: 'Yamuna floodplain overflow, severe urban heat island effect, and dense slum vulnerability',
  },
  {
    name: 'Karnataka',
    state: 'Karnataka',
    country: 'India',
    category: 'South India',
    population: 68000000,
    area: 191791,
    center: { lat: 14.50, lng: 75.70 },
    bounds: { north: 18.5, south: 11.6, east: 78.6, west: 74.0 },
    defaultZoom: 7,
    description: 'Kodagu / Western Ghats landslides, coastal Karwar/Udupi monsoon floods, and North Karnataka aridity',
  },
];
