// Demo safe relocation sites around Telangana
// These are fictional demo locations for hackathon purposes

export const safeSitesData = [
  {
    name: 'Green Valley Resettlement Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.498, 17.558] },
    elevation: 642,
    totalCapacity: 5000,
    occupiedCapacity: 1200,
    waterCapacity: 88,
    healthcareScore: 91,
    educationScore: 85,
    roadAccessibility: 87,
    infrastructureScore: 90,
    landAvailability: 82,
    hazardScore: 12,
    transportDistance: 18.4,
    transportCost: 320,
    safetyScore: 92,
    carryingCapacityScore: 88,
    overallSafetyScore: 91,
    description: 'Elevated plateau with excellent infrastructure, hospitals, schools, and stable terrain.',
    amenities: ['hospital', 'school', 'water_supply', 'roads', 'electricity', 'drainage'],
  },
  {
    name: 'North Ridge Shelter Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.612, 17.642] },
    elevation: 718,
    totalCapacity: 7500,
    occupiedCapacity: 2400,
    waterCapacity: 82,
    healthcareScore: 74,
    educationScore: 78,
    roadAccessibility: 93,
    infrastructureScore: 82,
    landAvailability: 90,
    hazardScore: 8,
    transportDistance: 25.1,
    transportCost: 280,
    safetyScore: 88,
    carryingCapacityScore: 94,
    overallSafetyScore: 86,
    description: 'Large resettlement zone on ridge with excellent road connectivity and ample land.',
    amenities: ['health_center', 'school', 'water_supply', 'roads', 'electricity'],
  },
  {
    name: 'Madhavapur Safe Campus',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.428, 17.488] },
    elevation: 595,
    totalCapacity: 3500,
    occupiedCapacity: 800,
    waterCapacity: 92,
    healthcareScore: 88,
    educationScore: 90,
    roadAccessibility: 79,
    infrastructureScore: 88,
    landAvailability: 72,
    hazardScore: 15,
    transportDistance: 12.2,
    transportCost: 420,
    safetyScore: 86,
    carryingCapacityScore: 78,
    overallSafetyScore: 84,
    description: 'Well-planned campus with premium facilities, closer to source settlements.',
    amenities: ['hospital', 'school', 'university', 'water_supply', 'roads', 'electricity', 'market'],
  },
  {
    name: 'River View Rehabilitation Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.548, 17.322] },
    elevation: 548,
    totalCapacity: 4200,
    occupiedCapacity: 1800,
    waterCapacity: 75,
    healthcareScore: 80,
    educationScore: 72,
    roadAccessibility: 84,
    infrastructureScore: 76,
    landAvailability: 68,
    hazardScore: 20,
    transportDistance: 22.8,
    transportCost: 360,
    safetyScore: 79,
    carryingCapacityScore: 72,
    overallSafetyScore: 77,
    description: 'Riverside plateau zone with good access and moderate capacity.',
    amenities: ['health_center', 'school', 'water_supply', 'roads', 'electricity'],
  },
  {
    name: 'Hilltop Community Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.682, 17.512] },
    elevation: 785,
    totalCapacity: 2800,
    occupiedCapacity: 400,
    waterCapacity: 70,
    healthcareScore: 82,
    educationScore: 68,
    roadAccessibility: 72,
    infrastructureScore: 74,
    landAvailability: 85,
    hazardScore: 6,
    transportDistance: 31.5,
    transportCost: 510,
    safetyScore: 94,
    carryingCapacityScore: 90,
    overallSafetyScore: 89,
    description: 'Highest elevation zone, exceptionally safe from floods and cyclones.',
    amenities: ['health_center', 'school', 'water_supply', 'roads', 'electricity'],
  },
  {
    name: 'Pragathi Nagar Safe Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.118, 17.448] },
    elevation: 612,
    totalCapacity: 6000,
    occupiedCapacity: 2200,
    waterCapacity: 85,
    healthcareScore: 86,
    educationScore: 82,
    roadAccessibility: 90,
    infrastructureScore: 84,
    landAvailability: 78,
    hazardScore: 14,
    transportDistance: 28.6,
    transportCost: 295,
    safetyScore: 87,
    carryingCapacityScore: 85,
    overallSafetyScore: 87,
    description: 'Modern planned resettlement area with government-backed infrastructure.',
    amenities: ['hospital', 'school', 'water_supply', 'roads', 'electricity', 'market', 'drainage'],
  },
  {
    name: 'Saraswati Plateau Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.348, 17.612] },
    elevation: 668,
    totalCapacity: 3800,
    occupiedCapacity: 950,
    waterCapacity: 90,
    healthcareScore: 78,
    educationScore: 88,
    roadAccessibility: 76,
    infrastructureScore: 80,
    landAvailability: 88,
    hazardScore: 10,
    transportDistance: 16.8,
    transportCost: 380,
    safetyScore: 90,
    carryingCapacityScore: 82,
    overallSafetyScore: 88,
    description: 'Education-focused resettlement zone with good schools and water availability.',
    amenities: ['health_center', 'school', 'college', 'water_supply', 'roads', 'electricity'],
  },
  {
    name: 'Kaveri Upland Settlement',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.248, 17.682] },
    elevation: 582,
    totalCapacity: 4500,
    occupiedCapacity: 1600,
    waterCapacity: 78,
    healthcareScore: 84,
    educationScore: 76,
    roadAccessibility: 88,
    infrastructureScore: 78,
    landAvailability: 72,
    hazardScore: 18,
    transportDistance: 35.2,
    transportCost: 265,
    safetyScore: 82,
    carryingCapacityScore: 76,
    overallSafetyScore: 81,
    description: 'Regional safe zone serving eastern Telangana settlements.',
    amenities: ['hospital', 'school', 'water_supply', 'roads', 'electricity', 'market'],
  },
  {
    name: 'Deccan Safe Corridor',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.758, 17.288] },
    elevation: 628,
    totalCapacity: 5500,
    occupiedCapacity: 2800,
    waterCapacity: 72,
    healthcareScore: 76,
    educationScore: 74,
    roadAccessibility: 92,
    infrastructureScore: 72,
    landAvailability: 65,
    hazardScore: 22,
    transportDistance: 20.4,
    transportCost: 310,
    safetyScore: 78,
    carryingCapacityScore: 68,
    overallSafetyScore: 76,
    description: 'High-capacity corridor with excellent road access for large-scale relocations.',
    amenities: ['health_center', 'school', 'water_supply', 'roads', 'electricity'],
  },
  {
    name: 'Shanti Valley Camp',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [77.842, 17.758] },
    elevation: 558,
    totalCapacity: 2500,
    occupiedCapacity: 320,
    waterCapacity: 88,
    healthcareScore: 72,
    educationScore: 80,
    roadAccessibility: 68,
    infrastructureScore: 70,
    landAvailability: 92,
    hazardScore: 8,
    transportDistance: 42.1,
    transportCost: 580,
    safetyScore: 91,
    carryingCapacityScore: 88,
    overallSafetyScore: 85,
    description: 'Remote high-safety zone ideal for long-term permanent resettlement.',
    amenities: ['health_center', 'school', 'water_supply', 'roads', 'electricity'],
  },
  {
    name: 'Eastern Highlands Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [80.012, 17.558] },
    elevation: 695,
    totalCapacity: 4800,
    occupiedCapacity: 1200,
    waterCapacity: 82,
    healthcareScore: 80,
    educationScore: 78,
    roadAccessibility: 82,
    infrastructureScore: 80,
    landAvailability: 80,
    hazardScore: 12,
    transportDistance: 38.8,
    transportCost: 245,
    safetyScore: 88,
    carryingCapacityScore: 84,
    overallSafetyScore: 87,
    description: 'Eastern zone serving Khammam and Bhadrachalam at-risk areas.',
    amenities: ['hospital', 'school', 'water_supply', 'roads', 'electricity', 'market'],
  },
  {
    name: 'Telangana Model Township',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.882, 17.858] },
    elevation: 452,
    totalCapacity: 8000,
    occupiedCapacity: 3200,
    waterCapacity: 88,
    healthcareScore: 90,
    educationScore: 92,
    roadAccessibility: 95,
    infrastructureScore: 92,
    landAvailability: 70,
    hazardScore: 16,
    transportDistance: 32.5,
    transportCost: 290,
    safetyScore: 85,
    carryingCapacityScore: 72,
    overallSafetyScore: 83,
    description: 'Government model township with premium infrastructure and large capacity.',
    amenities: ['hospital', 'school', 'college', 'water_supply', 'roads', 'electricity', 'market', 'drainage', 'recreation'],
  },
  {
    name: 'Nallamala Foothills Camp',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.448, 16.912] },
    elevation: 438,
    totalCapacity: 3200,
    occupiedCapacity: 600,
    waterCapacity: 85,
    healthcareScore: 70,
    educationScore: 72,
    roadAccessibility: 75,
    infrastructureScore: 72,
    landAvailability: 88,
    hazardScore: 14,
    transportDistance: 28.2,
    transportCost: 350,
    safetyScore: 85,
    carryingCapacityScore: 86,
    overallSafetyScore: 83,
    description: 'Natural highland area south of Telangana serving Nalgonda relocation needs.',
    amenities: ['health_center', 'school', 'water_supply', 'roads', 'electricity'],
  },
  {
    name: 'Medchal Heights Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.488, 17.628] },
    elevation: 608,
    totalCapacity: 6500,
    occupiedCapacity: 2800,
    waterCapacity: 86,
    healthcareScore: 88,
    educationScore: 86,
    roadAccessibility: 92,
    infrastructureScore: 86,
    landAvailability: 68,
    hazardScore: 14,
    transportDistance: 14.2,
    transportCost: 340,
    safetyScore: 87,
    carryingCapacityScore: 76,
    overallSafetyScore: 85,
    description: 'Urban fringe safe zone near Hyderabad with excellent connectivity.',
    amenities: ['hospital', 'school', 'water_supply', 'roads', 'electricity', 'market', 'drainage'],
  },
  {
    name: 'Bhongir Elevated Camp',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.905, 17.582] },
    elevation: 480,
    totalCapacity: 3000,
    occupiedCapacity: 700,
    waterCapacity: 80,
    healthcareScore: 76,
    educationScore: 74,
    roadAccessibility: 85,
    infrastructureScore: 76,
    landAvailability: 82,
    hazardScore: 18,
    transportDistance: 22.0,
    transportCost: 330,
    safetyScore: 82,
    carryingCapacityScore: 80,
    overallSafetyScore: 80,
    description: 'Centrally located zone serving Warangal and Bhongir area settlements.',
    amenities: ['health_center', 'school', 'water_supply', 'roads', 'electricity'],
  },
];
