// Demo settlements around Telangana region
// Coordinates centered around Hyderabad area (17.385°N, 78.486°E)
// These are fictional demo locations for hackathon purposes

export const settlementsData = [
  {
    name: 'Rampur Colony',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.312, 17.445] },
    elevation: 512,
    population: 4820,
    children: 1250,
    elderly: 620,
    disabled: 180,
    lowIncome: 2100,
    pregnantWomen: 95,
    floodRisk: 88,
    landslideRisk: 42,
    cycloneRisk: 65,
    heatRisk: 72,
    infrastructureRisk: 78,
    roadAccessibility: 28,
    healthcareAccess: 22,
    educationAccess: 35,
    waterAccess: 30,
    hazardScore: 78,
    riskLevel: 'CRITICAL',
    priorityScore: 91,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Lakshmipur Village',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.285, 17.398] },
    elevation: 489,
    population: 3210,
    children: 820,
    elderly: 410,
    disabled: 120,
    lowIncome: 1450,
    pregnantWomen: 64,
    floodRisk: 82,
    landslideRisk: 55,
    cycloneRisk: 58,
    heatRisk: 68,
    infrastructureRisk: 72,
    roadAccessibility: 32,
    healthcareAccess: 28,
    educationAccess: 40,
    waterAccess: 35,
    hazardScore: 72,
    riskLevel: 'CRITICAL',
    priorityScore: 84,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Devapur Settlement',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.354, 17.362] },
    elevation: 534,
    population: 2890,
    children: 710,
    elderly: 380,
    disabled: 95,
    lowIncome: 1200,
    pregnantWomen: 55,
    floodRisk: 75,
    landslideRisk: 68,
    cycloneRisk: 52,
    heatRisk: 64,
    infrastructureRisk: 65,
    roadAccessibility: 38,
    healthcareAccess: 35,
    educationAccess: 45,
    waterAccess: 42,
    hazardScore: 68,
    riskLevel: 'HIGH',
    priorityScore: 76,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Kothapalli Township',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.401, 17.428] },
    elevation: 498,
    population: 6540,
    children: 1680,
    elderly: 845,
    disabled: 240,
    lowIncome: 2800,
    pregnantWomen: 128,
    floodRisk: 70,
    landslideRisk: 35,
    cycloneRisk: 72,
    heatRisk: 66,
    infrastructureRisk: 60,
    roadAccessibility: 45,
    healthcareAccess: 42,
    educationAccess: 55,
    waterAccess: 48,
    hazardScore: 63,
    riskLevel: 'HIGH',
    priorityScore: 71,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Nandigama Hamlet',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.268, 17.471] },
    elevation: 478,
    population: 1850,
    children: 480,
    elderly: 240,
    disabled: 72,
    lowIncome: 920,
    pregnantWomen: 38,
    floodRisk: 92,
    landslideRisk: 28,
    cycloneRisk: 60,
    heatRisk: 58,
    infrastructureRisk: 82,
    roadAccessibility: 20,
    healthcareAccess: 18,
    educationAccess: 25,
    waterAccess: 22,
    hazardScore: 82,
    riskLevel: 'CRITICAL',
    priorityScore: 94,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Rajapur Ward',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.332, 17.415] },
    elevation: 521,
    population: 3680,
    children: 945,
    elderly: 475,
    disabled: 138,
    lowIncome: 1580,
    pregnantWomen: 72,
    floodRisk: 65,
    landslideRisk: 48,
    cycloneRisk: 55,
    heatRisk: 75,
    infrastructureRisk: 58,
    roadAccessibility: 52,
    healthcareAccess: 48,
    educationAccess: 58,
    waterAccess: 55,
    hazardScore: 61,
    riskLevel: 'HIGH',
    priorityScore: 68,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Suryapet Outskirts',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.612, 17.142] },
    elevation: 102,
    population: 5120,
    children: 1320,
    elderly: 660,
    disabled: 195,
    lowIncome: 2200,
    pregnantWomen: 102,
    floodRisk: 95,
    landslideRisk: 20,
    cycloneRisk: 45,
    heatRisk: 80,
    infrastructureRisk: 70,
    roadAccessibility: 35,
    healthcareAccess: 30,
    educationAccess: 42,
    waterAccess: 28,
    hazardScore: 80,
    riskLevel: 'CRITICAL',
    priorityScore: 88,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Bhongir North',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.888, 17.509] },
    elevation: 382,
    population: 4280,
    children: 1095,
    elderly: 550,
    disabled: 160,
    lowIncome: 1840,
    pregnantWomen: 85,
    floodRisk: 55,
    landslideRisk: 72,
    cycloneRisk: 40,
    heatRisk: 68,
    infrastructureRisk: 55,
    roadAccessibility: 60,
    healthcareAccess: 55,
    educationAccess: 65,
    waterAccess: 62,
    hazardScore: 58,
    riskLevel: 'HIGH',
    priorityScore: 62,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Miryalaguda Basin',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.565, 16.872] },
    elevation: 86,
    population: 7240,
    children: 1850,
    elderly: 935,
    disabled: 272,
    lowIncome: 3100,
    pregnantWomen: 145,
    floodRisk: 90,
    landslideRisk: 18,
    cycloneRisk: 48,
    heatRisk: 82,
    infrastructureRisk: 75,
    roadAccessibility: 42,
    healthcareAccess: 38,
    educationAccess: 50,
    waterAccess: 35,
    hazardScore: 77,
    riskLevel: 'CRITICAL',
    priorityScore: 85,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Nalgonda Riverside',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.262, 17.058] },
    elevation: 132,
    population: 3940,
    children: 1010,
    elderly: 508,
    disabled: 148,
    lowIncome: 1690,
    pregnantWomen: 78,
    floodRisk: 85,
    landslideRisk: 22,
    cycloneRisk: 42,
    heatRisk: 76,
    infrastructureRisk: 68,
    roadAccessibility: 48,
    healthcareAccess: 44,
    educationAccess: 55,
    waterAccess: 40,
    hazardScore: 73,
    riskLevel: 'CRITICAL',
    priorityScore: 80,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Siddipet Eastern',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.851, 18.101] },
    elevation: 285,
    population: 2650,
    children: 680,
    elderly: 340,
    disabled: 100,
    lowIncome: 1140,
    pregnantWomen: 52,
    floodRisk: 48,
    landslideRisk: 38,
    cycloneRisk: 62,
    heatRisk: 55,
    infrastructureRisk: 45,
    roadAccessibility: 68,
    healthcareAccess: 62,
    educationAccess: 70,
    waterAccess: 72,
    hazardScore: 50,
    riskLevel: 'MODERATE',
    priorityScore: 54,
    priorityLevel: 'MEDIUM',
  },
  {
    name: 'Medak Lowlands',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [77.985, 18.048] },
    elevation: 418,
    population: 3180,
    children: 815,
    elderly: 410,
    disabled: 120,
    lowIncome: 1365,
    pregnantWomen: 63,
    floodRisk: 58,
    landslideRisk: 45,
    cycloneRisk: 52,
    heatRisk: 62,
    infrastructureRisk: 52,
    roadAccessibility: 62,
    healthcareAccess: 58,
    educationAccess: 68,
    waterAccess: 65,
    hazardScore: 54,
    riskLevel: 'HIGH',
    priorityScore: 58,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Karimnagar Floodplain',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.128, 18.438] },
    elevation: 248,
    population: 5890,
    children: 1510,
    elderly: 758,
    disabled: 220,
    lowIncome: 2530,
    pregnantWomen: 118,
    floodRisk: 80,
    landslideRisk: 30,
    cycloneRisk: 55,
    heatRisk: 70,
    infrastructureRisk: 65,
    roadAccessibility: 55,
    healthcareAccess: 52,
    educationAccess: 62,
    waterAccess: 50,
    hazardScore: 69,
    riskLevel: 'HIGH',
    priorityScore: 74,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Nizamabad Valley',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.094, 18.672] },
    elevation: 358,
    population: 4120,
    children: 1056,
    elderly: 530,
    disabled: 155,
    lowIncome: 1770,
    pregnantWomen: 82,
    floodRisk: 62,
    landslideRisk: 52,
    cycloneRisk: 48,
    heatRisk: 65,
    infrastructureRisk: 58,
    roadAccessibility: 65,
    healthcareAccess: 60,
    educationAccess: 72,
    waterAccess: 68,
    hazardScore: 57,
    riskLevel: 'HIGH',
    priorityScore: 61,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Warangal South',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.578, 17.978] },
    elevation: 295,
    population: 6280,
    children: 1610,
    elderly: 808,
    disabled: 235,
    lowIncome: 2700,
    pregnantWomen: 125,
    floodRisk: 55,
    landslideRisk: 35,
    cycloneRisk: 68,
    heatRisk: 72,
    infrastructureRisk: 48,
    roadAccessibility: 72,
    healthcareAccess: 68,
    educationAccess: 78,
    waterAccess: 75,
    hazardScore: 55,
    riskLevel: 'HIGH',
    priorityScore: 58,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Mancherial Gorge',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.444, 18.872] },
    elevation: 148,
    population: 2840,
    children: 728,
    elderly: 365,
    disabled: 107,
    lowIncome: 1220,
    pregnantWomen: 57,
    floodRisk: 72,
    landslideRisk: 78,
    cycloneRisk: 35,
    heatRisk: 58,
    infrastructureRisk: 68,
    roadAccessibility: 38,
    healthcareAccess: 32,
    educationAccess: 45,
    waterAccess: 38,
    hazardScore: 67,
    riskLevel: 'HIGH',
    priorityScore: 72,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Adilabad Tribal Area',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.532, 19.664] },
    elevation: 298,
    population: 1920,
    children: 492,
    elderly: 246,
    disabled: 72,
    lowIncome: 1580,
    pregnantWomen: 38,
    floodRisk: 45,
    landslideRisk: 82,
    cycloneRisk: 30,
    heatRisk: 50,
    infrastructureRisk: 78,
    roadAccessibility: 22,
    healthcareAccess: 18,
    educationAccess: 28,
    waterAccess: 32,
    hazardScore: 63,
    riskLevel: 'HIGH',
    priorityScore: 78,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Khammam Lowland',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [80.152, 17.248] },
    elevation: 110,
    population: 8240,
    children: 2112,
    elderly: 1056,
    disabled: 308,
    lowIncome: 3540,
    pregnantWomen: 165,
    floodRisk: 88,
    landslideRisk: 25,
    cycloneRisk: 58,
    heatRisk: 78,
    infrastructureRisk: 72,
    roadAccessibility: 48,
    healthcareAccess: 45,
    educationAccess: 58,
    waterAccess: 42,
    hazardScore: 76,
    riskLevel: 'CRITICAL',
    priorityScore: 82,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Bhadrachalam Riverside',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [80.894, 17.669] },
    elevation: 62,
    population: 3560,
    children: 912,
    elderly: 458,
    disabled: 133,
    lowIncome: 1530,
    pregnantWomen: 71,
    floodRisk: 94,
    landslideRisk: 32,
    cycloneRisk: 52,
    heatRisk: 68,
    infrastructureRisk: 78,
    roadAccessibility: 32,
    healthcareAccess: 28,
    educationAccess: 38,
    waterAccess: 25,
    hazardScore: 81,
    riskLevel: 'CRITICAL',
    priorityScore: 89,
    priorityLevel: 'URGENT',
  },
  {
    name: 'Mahabubnagar Plains',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [77.987, 16.735] },
    elevation: 432,
    population: 4980,
    children: 1276,
    elderly: 640,
    disabled: 187,
    lowIncome: 2140,
    pregnantWomen: 100,
    floodRisk: 52,
    landslideRisk: 28,
    cycloneRisk: 65,
    heatRisk: 88,
    infrastructureRisk: 55,
    roadAccessibility: 58,
    healthcareAccess: 52,
    educationAccess: 64,
    waterAccess: 55,
    hazardScore: 58,
    riskLevel: 'HIGH',
    priorityScore: 62,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Jadcherla Drought Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.178, 16.548] },
    elevation: 485,
    population: 2340,
    children: 600,
    elderly: 300,
    disabled: 88,
    lowIncome: 1950,
    pregnantWomen: 47,
    floodRisk: 35,
    landslideRisk: 22,
    cycloneRisk: 58,
    heatRisk: 92,
    infrastructureRisk: 62,
    roadAccessibility: 55,
    healthcareAccess: 48,
    educationAccess: 58,
    waterAccess: 30,
    hazardScore: 52,
    riskLevel: 'HIGH',
    priorityScore: 60,
    priorityLevel: 'HIGH',
  },
  {
    name: 'Wanaparthy Hills',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.065, 16.362] },
    elevation: 552,
    population: 1680,
    children: 430,
    elderly: 216,
    disabled: 64,
    lowIncome: 720,
    pregnantWomen: 34,
    floodRisk: 28,
    landslideRisk: 65,
    cycloneRisk: 42,
    heatRisk: 70,
    infrastructureRisk: 48,
    roadAccessibility: 70,
    healthcareAccess: 65,
    educationAccess: 75,
    waterAccess: 78,
    hazardScore: 44,
    riskLevel: 'MODERATE',
    priorityScore: 46,
    priorityLevel: 'MEDIUM',
  },
  {
    name: 'Narayanpet Market Area',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [77.498, 16.742] },
    elevation: 508,
    population: 3120,
    children: 800,
    elderly: 400,
    disabled: 118,
    lowIncome: 1340,
    pregnantWomen: 62,
    floodRisk: 42,
    landslideRisk: 30,
    cycloneRisk: 55,
    heatRisk: 85,
    infrastructureRisk: 50,
    roadAccessibility: 72,
    healthcareAccess: 68,
    educationAccess: 78,
    waterAccess: 65,
    hazardScore: 49,
    riskLevel: 'MODERATE',
    priorityScore: 52,
    priorityLevel: 'MEDIUM',
  },
  {
    name: 'Sangareddy New Colony',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [77.918, 17.618] },
    elevation: 462,
    population: 4560,
    children: 1168,
    elderly: 586,
    disabled: 171,
    lowIncome: 1960,
    pregnantWomen: 91,
    floodRisk: 48,
    landslideRisk: 32,
    cycloneRisk: 62,
    heatRisk: 72,
    infrastructureRisk: 45,
    roadAccessibility: 75,
    healthcareAccess: 72,
    educationAccess: 80,
    waterAccess: 78,
    hazardScore: 48,
    riskLevel: 'MODERATE',
    priorityScore: 50,
    priorityLevel: 'MEDIUM',
  },
  {
    name: 'Zahirabad Dry Belt',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [77.608, 17.682] },
    elevation: 492,
    population: 2780,
    children: 712,
    elderly: 357,
    disabled: 105,
    lowIncome: 1195,
    pregnantWomen: 56,
    floodRisk: 32,
    landslideRisk: 25,
    cycloneRisk: 48,
    heatRisk: 88,
    infrastructureRisk: 55,
    roadAccessibility: 65,
    healthcareAccess: 60,
    educationAccess: 70,
    waterAccess: 35,
    hazardScore: 46,
    riskLevel: 'MODERATE',
    priorityScore: 50,
    priorityLevel: 'MEDIUM',
  },
  {
    name: 'Vikarabad Green Zone',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [77.902, 17.338] },
    elevation: 618,
    population: 2180,
    children: 558,
    elderly: 280,
    disabled: 82,
    lowIncome: 940,
    pregnantWomen: 44,
    floodRisk: 22,
    landslideRisk: 45,
    cycloneRisk: 35,
    heatRisk: 48,
    infrastructureRisk: 30,
    roadAccessibility: 82,
    healthcareAccess: 78,
    educationAccess: 85,
    waterAccess: 88,
    hazardScore: 30,
    riskLevel: 'MODERATE',
    priorityScore: 32,
    priorityLevel: 'LOW',
  },
  {
    name: 'Patancheru Industrial',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.265, 17.535] },
    elevation: 555,
    population: 3850,
    children: 986,
    elderly: 495,
    disabled: 145,
    lowIncome: 1656,
    pregnantWomen: 77,
    floodRisk: 38,
    landslideRisk: 18,
    cycloneRisk: 58,
    heatRisk: 75,
    infrastructureRisk: 42,
    roadAccessibility: 85,
    healthcareAccess: 80,
    educationAccess: 88,
    waterAccess: 82,
    hazardScore: 42,
    riskLevel: 'MODERATE',
    priorityScore: 44,
    priorityLevel: 'MEDIUM',
  },
  {
    name: 'Yadagirigutta Foothills',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.025, 17.602] },
    elevation: 345,
    population: 1920,
    children: 492,
    elderly: 246,
    disabled: 72,
    lowIncome: 826,
    pregnantWomen: 38,
    floodRisk: 30,
    landslideRisk: 58,
    cycloneRisk: 38,
    heatRisk: 52,
    infrastructureRisk: 38,
    roadAccessibility: 78,
    healthcareAccess: 74,
    educationAccess: 82,
    waterAccess: 80,
    hazardScore: 38,
    riskLevel: 'MODERATE',
    priorityScore: 40,
    priorityLevel: 'MEDIUM',
  },
  {
    name: 'Jangaon Safe Plateau',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [79.152, 17.722] },
    elevation: 398,
    population: 3240,
    children: 830,
    elderly: 416,
    disabled: 122,
    lowIncome: 1392,
    pregnantWomen: 65,
    floodRisk: 25,
    landslideRisk: 20,
    cycloneRisk: 42,
    heatRisk: 55,
    infrastructureRisk: 28,
    roadAccessibility: 88,
    healthcareAccess: 85,
    educationAccess: 90,
    waterAccess: 88,
    hazardScore: 28,
    riskLevel: 'MODERATE',
    priorityScore: 30,
    priorityLevel: 'LOW',
  },
  {
    name: 'Uppal Upland',
    regionName: 'Telangana',
    location: { type: 'Point', coordinates: [78.558, 17.405] },
    elevation: 495,
    population: 5120,
    children: 1312,
    elderly: 656,
    disabled: 192,
    lowIncome: 2202,
    pregnantWomen: 102,
    floodRisk: 20,
    landslideRisk: 15,
    cycloneRisk: 38,
    heatRisk: 60,
    infrastructureRisk: 22,
    roadAccessibility: 92,
    healthcareAccess: 90,
    educationAccess: 92,
    waterAccess: 90,
    hazardScore: 22,
    riskLevel: 'SAFE',
    priorityScore: 18,
    priorityLevel: 'LOW',
  },
];
