/**
 * Fallback AI Service
 * Deterministic explanations when no AI API key is available
 * Produces useful demo output from pre-calculated scores
 */

export const generateFallbackRiskExplanation = (data) => {
  const { settlement, riskResult, priorityResult } = data;
  const { score, level, factors } = riskResult;

  const topHazards = Object.entries({
    'Flood exposure': settlement.floodRisk,
    'Landslide risk': settlement.landslideRisk,
    'Cyclone/wind exposure': settlement.cycloneRisk,
    'Extreme heat': settlement.heatRisk,
    'Infrastructure vulnerability': settlement.infrastructureRisk,
  })
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([name, score]) => `${name} (${score}/100)`);

  const accessGaps = [];
  if (settlement.roadAccessibility < 40) accessGaps.push('limited road connectivity');
  if (settlement.healthcareAccess < 40) accessGaps.push('poor healthcare access');
  if (settlement.waterAccess < 40) accessGaps.push('inadequate water supply');

  const totalVulnerable = settlement.children + settlement.elderly + settlement.disabled + (settlement.pregnantWomen || 0);
  const vulnerabilityPercent = Math.round((totalVulnerable / settlement.population) * 100);

  const riskNarrative = {
    CRITICAL: `${settlement.name} faces a critical multi-hazard risk situation that demands immediate attention. The composite risk score of ${score}/100 is driven by ${topHazards.join(', ')}.`,
    HIGH: `${settlement.name} is classified as high-risk with a composite score of ${score}/100. Primary hazard drivers are ${topHazards.join(', ')}.`,
    MODERATE: `${settlement.name} carries moderate risk (${score}/100). The main contributing factors are ${topHazards.join(', ')}.`,
    SAFE: `${settlement.name} currently shows manageable risk levels (${score}/100), though monitoring is recommended for ${topHazards[0]}.`,
  }[level];

  const vulnerabilityNarrative = `Approximately ${totalVulnerable.toLocaleString()} people (${vulnerabilityPercent}% of population) belong to vulnerable groups including ${settlement.children.toLocaleString()} children, ${settlement.elderly.toLocaleString()} elderly residents, and ${settlement.disabled.toLocaleString()} persons with disabilities.${settlement.lowIncome > 0 ? ` An additional ${settlement.lowIncome.toLocaleString()} low-income households face compounded risk due to limited resources for self-evacuation.` : ''}`;

  const accessNarrative = accessGaps.length > 0
    ? `Infrastructure assessment reveals ${accessGaps.join(' and ')}, which would significantly impede emergency response and evacuation.`
    : `Road and healthcare accessibility are at acceptable levels, supporting efficient emergency response.`;

  const actionNarrative = priorityResult.priorityLevel === 'URGENT'
    ? `Immediate evacuation planning is recommended. Pre-position emergency response assets and notify district disaster management authority. Transport requirements should be assessed for ${settlement.population.toLocaleString()} residents.`
    : priorityResult.priorityLevel === 'HIGH'
      ? `Planned relocation should begin within 2 weeks. Engage with safe site administrators and assess transport logistics for ${settlement.population.toLocaleString()} residents.`
      : `Continue monitoring and develop contingency evacuation plans. Conduct community awareness programs.`;

  return `**RISK EXPLANATION**
${riskNarrative}

**VULNERABLE POPULATION**
${vulnerabilityNarrative}

**INFRASTRUCTURE ASSESSMENT**
${accessNarrative}

**RECOMMENDED ACTIONS**
${actionNarrative}

**RELOCATION ASSESSMENT**
${priorityResult.recommendedAction}

*Note: This analysis is generated by the HazardShield deterministic risk engine. AI API integration will provide enhanced narrative analysis when configured.*`;
};

export const generateFallbackRelocationRecommendation = (data) => {
  const { settlement, recommendations } = data;
  const top = recommendations[0];
  const second = recommendations[1];

  if (!top) return 'No suitable safe sites found with sufficient capacity. Contact regional disaster management authority.';

  const feasibilityNote = top.feasibility.feasible
    ? `Site ${top.site.name} can accommodate all ${settlement.population.toLocaleString()} residents with ${top.feasibility.remainingCapacity.toLocaleString()} capacity remaining.`
    : `No single site has full capacity. A phased relocation approach is recommended, prioritising vulnerable groups first.`;

  const comparisonNote = second
    ? `Alternative site ${second.site.name} scores ${second.candidateScore}/100 versus ${top.candidateScore}/100 for the primary recommendation. ${second.site.safetyScore > top.site.safetyScore ? `Site ${second.site.name} offers higher safety (${second.site.safetyScore}/100) but at greater distance (${second.distance}km).` : `Site ${top.site.name} is preferred for its combined safety and capacity balance.`}`
    : '';

  return `**RECOMMENDED RELOCATION SITE: ${top.site.name}**

Algorithm score: ${top.candidateScore}/100 — ranked highest among ${data.recommendations.length} candidate sites.

${feasibilityNote}

**KEY FACTORS:**
• Safety score: ${top.site.safetyScore}/100 (+${top.safetyImprovement}% improvement from current location)
• Distance: ${top.distance}km — estimated travel time ~${top.transport.travelTimeMinutes} minutes
• Estimated transport cost: ₹${top.transport.totalCost.toLocaleString()} (${top.transport.vehiclesRequired} vehicles, ${top.transport.tripsRequired} trips)
• Healthcare access: ${top.site.healthcareScore}/100
• Road accessibility: ${top.site.roadAccessibility}/100

${comparisonNote}

**OPERATIONAL NOTE:** Coordinate with district administration for vehicle procurement. Prioritise children, elderly, and disabled residents in first transport wave.

*Generated by HazardShield Relocation Optimizer. Values are planning estimates.*`;
};

export const generateFallbackEmergencyPlan = (data) => {
  const { settlement, riskResult, simulationResult } = data;
  const name = settlement?.name || 'Affected Region';
  const simData = simulationResult?.simulated || {};

  return `**EMERGENCY ACTION PLAN — ${name.toUpperCase()}**

**IMMEDIATE ACTIONS (0-6 hours)**
• Activate district emergency operations centre and alert all field teams
• Issue public warnings via SMS, sirens, and community announcements
• Pre-position ${simData.relocationDemand ? Math.ceil(simData.relocationDemand / 50) : 20}+ vehicles at assembly points
• Deploy first-response medical teams to all vulnerable-population clusters
• Establish command post at nearest accessible government facility

**24-HOUR ACTIONS**
• Begin priority evacuation: children, elderly, disabled, pregnant women first
• Open all designated safe sites and assign reception coordinators
• Establish emergency food/water distribution at 3 key relief points
• Restore or create alternative access routes if main roads are compromised
• Set up emergency helpline and family tracking system

**7-DAY ACTIONS**
• Complete evacuation of all URGENT and HIGH priority zones
• Conduct damage assessment for housing and infrastructure
• Establish temporary schools and healthcare facilities at safe sites
• Begin psychological support services for displaced families
• Submit official disaster declaration with resource requirements

**LONG-TERM MITIGATION (30 days+)**
• Develop permanent resettlement infrastructure at designated safe sites
• Construct flood/cyclone-resilient housing meeting hazard-specific standards
• Upgrade evacuation road network with all-weather surfacing
• Install early warning sensors in all high-risk zones
• Launch community disaster preparedness training for 10,000+ residents

${simData.capacityGap > 0 ? `\n⚠️ CAPACITY ALERT: ${simData.capacityGap.toLocaleString()} person shelter gap identified — activate mutual aid agreements with neighbouring districts immediately.` : ''}

*Plan generated by HazardShield AI Emergency Planning Module. Adapt to actual ground conditions.*`;
};

export const generateFallbackReport = (data) => {
  const { region, stats, topSettlements, topSafeSites } = data;

  return {
    executiveSummary: `${region} faces a multi-hazard risk situation with ${stats.criticalZones} critical zones and ${stats.populationAtRisk?.toLocaleString()} residents at elevated risk. Immediate action is required for ${topSettlements.filter(s => s.riskLevel === 'CRITICAL').length} CRITICAL settlements while ${stats.totalSafeCapacity?.toLocaleString()} capacity is available across ${stats.safeSitesCount} safe sites.`,
    riskAssessment: `Regional analysis reveals compound hazard exposure from flooding, extreme heat, cyclone wind corridors, and landslide-prone terrain. Primary flood zones are concentrated along Krishna and Godavari river corridors. Heat stress is critical in southern districts. The composite risk score exceeds 75 for ${stats.criticalZones} zones, indicating immediate intervention requirements.`,
    criticalSettlements: topSettlements.slice(0, 5).map(s => `${s.name}: Risk ${s.hazardScore}/100, Pop ${s.population?.toLocaleString()}`),
    recommendedRelocations: topSettlements.filter(s => s.riskLevel === 'CRITICAL').slice(0, 4).map(s => `${s.name} → Nearest safe site (${s.population?.toLocaleString()} residents)`),
    safeSites: topSafeSites.slice(0, 4).map(s => `${s.name}: Safety ${s.safetyScore}/100, Available ${(s.totalCapacity - s.occupiedCapacity)?.toLocaleString()}`),
    infrastructureGaps: ['Inadequate evacuation roads in eastern flood zones', 'Healthcare access below threshold in 8 settlements', 'Water supply deficit in 6 high-risk areas', 'No early warning infrastructure in tribal zones'],
    immediateActions: ['Activate regional emergency operations centre', 'Issue evacuation orders for CRITICAL-rated settlements', 'Pre-position 200+ transport vehicles at assembly points', 'Alert all safe site administrators to receive populations', 'Deploy emergency medical teams to 5 critical zones'],
    longTermRecommendations: ['Develop permanent resettlement at 3 priority safe sites (5-year plan)', 'Construct elevated all-weather road network to isolated settlements', 'Install IoT flood and landslide sensors across 20 high-risk zones', 'Establish community disaster response networks in all 30 settlements', 'Develop hazard-resilient housing standards for all new construction'],
  };
};
